version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Thobui1996@
      - POSTGRES_DB=group-sync
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  group-sync:
    build:
      context: ./../group-sync
      dockerfile: Dockerfile
    container_name: group-sync
    restart: always
    depends_on:
      - postgres
    environment:
      - PORT=10000
      - DB_TYPE=mysql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASS=Thobui1996@
      - DB_NAME=group-sync
      - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - '10000:10000'

volumes:
  postgres-volume:
    driver: local
