version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=111111
      - POSTGRES_DB=group-sync
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  group-sync:
    build:
      context: ./../group-sync
      dockerfile: Dockerfile
    container_name: group-sync
    restart: always
    depends_on:
      - redis
    environment:
      - PORT=9000
      - DB_TYPE=mysql
      - DB_HOST=91.99.31.157
      - DB_PORT=3306
      - DB_USER_NAME=root
      - DB_PASSWORD=HoangChuong@1111
      - DB_DATABASE=crawl-fb
      - NODE_OPTIONS=--max-old-space-size=4096
      # redis
      - REDIS_HOST=redis
      - REDIS_PORT=6380
      - REDIS_TYPE=single
    ports:
      - '9000:9000'

  redis:
    image: redis:latest
    container_name: redis-group
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
  postgres-volume:
    driver: local
