version: '3'
services:
  tiktok-sync:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: group-sync
    restart: always
    environment:
      - PORT=8000
      - DB_TYPE=mysql
      - DB_HOST=103.67.196.23
      - DB_PORT=3306
      - DB_USER_NAME=root
      - DB_PASSWORD=Thanhtho96@1111
      - DB_DATABASE=homstay
      - NODE_OPTIONS=--max-old-space-size=4096
      - ENV=production
      - REDIS_HOST=103.67.196.23
      - REDIS_PORT=6379
      - REDIS_TYPE=single
    ports:
      - '8000:8000'
